development:
  sessions:
    default:      
      database: rails_settings_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: rails_settings_test
      hosts:
        - localhost:27017